// Shared course data for consistency across the application
export interface Course {
    id: number;
    degree: string;
    university: string;
    country: string;
    description: string;
    fullDescription?: string;
    duration: string;
    tuitionFee?: string;
    intake?: string;
    image: string;
    tags?: string[];
    requirements?: string[];
    highlights?: string[];
}

export const coursesData: Course[] = [
    // --- SOUTH KOREA UNIVERSITIES ---
    {
        id: 1,
        degree: 'Global Business & Management',
        university: 'Seoul National University',
        country: 'South Korea',
        description: 'Elite program at Korea\'s top-ranked university located in Gwanak-gu, Seoul.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80',
        tags: ['Ivy League of Korea', 'Top 1%'],
    },
    {
        id: 2,
        degree: 'Global Leadership Program',
        university: 'Yonsei University',
        country: 'South Korea',
        description: 'Prestigious SKY university program in Sinchon, Seoul, known for international excellence.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1622662991617-669e7ee4759b?auto=format&fit=crop&q=80',
        tags: ['SKY University', 'Beautiful Campus'],
    },
    {
        id: 3,
        degree: 'International Business',
        university: 'Korea University',
        country: 'South Korea',
        description: 'World-class education at one of Korea\'s oldest and most prestigious universities in Seoul.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1590012314607-cda9d3b36166?auto=format&fit=crop&q=80',
        tags: ['SKY University', 'Strong Alumni'],
    },
    {
        id: 4,
        degree: 'SMART Engineering',
        university: 'Ajou University',
        country: 'South Korea',
        description: 'Leading technical and research university based in Suwon, Gyeonggi.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80',
        tags: ['Inno-Campus', 'Near Seoul'],
    },
    {
        id: 5,
        degree: 'Automotive Engineering',
        university: 'Ajou Motor College',
        country: 'South Korea',
        description: 'Specialized automotive training in Boryeong, South Chungcheong.',
        duration: '2-4 Years',
        image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80',
        tags: ['Specialized', 'Technical'],
    },
    {
        id: 6,
        degree: 'International Trade',
        university: 'Busan University of Foreign Studies',
        country: 'South Korea',
        description: 'Diverse language and trade programs in the heart of Busan.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1578330132822-0466480e6f66?auto=format&fit=crop&q=80',
        tags: ['Languages', 'Port City'],
    },
    {
        id: 7,
        degree: 'Bio-Medical Sciences',
        university: 'Catholic University of Korea',
        country: 'South Korea',
        description: 'Historic institution in Seoul with a focus on humanities and sciences.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1516533037047-2854e47769dd?auto=format&fit=crop&q=80',
        tags: ['Clinical Excellence', 'Seoul'],
    },
    {
        id: 8,
        degree: 'Convergence Studies',
        university: 'Chung-Ang University',
        country: 'South Korea',
        description: 'Top-tier university with campuses in Seoul and Anseong.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1492538356227-227a7a29555e?auto=format&fit=crop&q=80',
        tags: ['Media/Arts', 'Central Seoul'],
    },
    {
        id: 9,
        degree: 'Digital Humanities',
        university: 'Sejong University',
        country: 'South Korea',
        description: 'Pioneer in hospitality and CS, located in Gwangjin-gu, Seoul.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80',
        tags: ['Hospitality', 'Seoul'],
    },
    {
        id: 10,
        degree: 'Global Business Management',
        university: 'Hanyang University',
        country: 'South Korea',
        description: 'Engineering powerhouse with a main campus in Seoul and ERICA campus in Ansan.',
        duration: '4 Years',
        image: 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&q=80',
        tags: ['Top Engineering', 'Ansan Campus'],
    },
    // Adding more from the list as requested
    { id: 11, degree: 'Public Administration', university: 'Chonnam National University', country: 'South Korea', description: 'Gwangju based flagship national university.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1523050853064-8e404bf7622d?auto=format&fit=crop&q=80', tags: ['National', 'Gwangju'] },
    { id: 12, degree: 'Agriculture & Life Sciences', university: 'Jeonbuk National University', country: 'South Korea', description: 'Dynamic national university in Jeonju, North Jeolla.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&q=80', tags: ['National', 'Jeonju'] },
    { id: 13, degree: 'Fine Arts & Design', university: 'Hongik University', country: 'South Korea', description: 'Famous for arts and design, located in the vibrant Seoul area.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&q=80', tags: ['Art/Design', 'Street Culture'] },
    { id: 14, degree: 'Logistics & Trade', university: 'Inha University', country: 'South Korea', description: 'Top-tier technical university based in Incheon.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80', tags: ['Incheon', 'Technical'] },
    { id: 15, degree: 'Hotel Management', university: 'Kyungpook National University', country: 'South Korea', description: 'Major national research university in Daegu.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80', tags: ['Research', 'Daegu'] },
    { id: 16, degree: 'Global Korean Studies', university: 'Sogang University', country: 'South Korea', description: 'Liberal arts focused university in the heart of Seoul.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80', tags: ['Elite', 'Mapo-gu'] },
    { id: 17, degree: 'IT & Convergence', university: 'Dankook University', country: 'South Korea', description: 'Campuses in Yongin and Cheonan with strong tradition.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80', tags: ['Yongin', 'Tradition'] },
    { id: 18, degree: 'Mechanical Engineering', university: 'Pusan National University', country: 'South Korea', description: 'Leading national university in the secondary capital Busan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80', tags: ['National', 'Busan'] },
    { id: 19, degree: 'Computer Science', university: 'Konkuk University', country: 'South Korea', description: 'Rapidly growing private university in Gwangjin-gu, Seoul.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80', tags: ['Seoul', 'Growing'] },
    { id: 20, degree: 'Aerospace Engineering', university: 'Korea Aerospace University', country: 'South Korea', description: 'Specialized aerospace focus in Goyang, Gyeonggi.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80', tags: ['Aerospace', 'Unique'] },
    { id: 21, degree: 'Ocean Sciences', university: 'Pukyong National University', country: 'South Korea', description: 'Oceanography and fisheries leader in Busan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80', tags: ['Ocean/Marine', 'Busan'] },
    { id: 22, degree: 'International Business', university: 'Dong-A University', country: 'South Korea', description: 'Prestigious private university in Busan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80', tags: ['Private', 'Busan'] },
    { id: 23, degree: 'Health Sciences', university: 'Inje University', country: 'South Korea', description: 'Medical and health focused university in Gimhae, Gyeongnam.', duration: '6 Years', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80', tags: ['Medical', 'Gimhae'] },
    { id: 24, degree: 'Information Technology', university: 'Gachon University', country: 'South Korea', description: 'Located in Seongnam, Gyeonggi, known for medical and engineering.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80', tags: ['Near Seoul', 'Medical'] },
    { id: 25, degree: 'Social Sciences', university: 'Chosun University', country: 'South Korea', description: 'Historic private university in Gwangju.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80', tags: ['Gwangju', 'Historic'] },
    { id: 26, degree: 'Global Management', university: 'Woosong University', country: 'South Korea', description: 'English-taught programs in Daejeon, SolBridge business school.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1434039345422-4e99e589ed8b?auto=format&fit=crop&q=80', tags: ['English Medium', 'Daejeon'] },
    { id: 27, degree: 'International Studies', university: 'Ewha Womans University', country: 'South Korea', description: 'Premier women\'s university in Seoul with a global reputation.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1544465544-1b71aee9dfa3?auto=format&fit=crop&q=80', tags: ['Women only', 'Top Tier'] },
    { id: 28, degree: 'Languages & Culture', university: 'HUFS', country: 'South Korea', description: 'Hankuk University of Foreign Studies, specializing in international relations.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80', tags: ['Diplomacy', 'Languages'] },
    { id: 29, degree: 'Smart Logistics', university: 'Pyeongtaek University', country: 'South Korea', description: 'Strategically located in Pyeongtaek, Gyeonggi, near major industrial hubs.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80', tags: ['Pyeongtaek', 'Near Seoul'] },
    { id: 30, degree: 'Visual Arts', university: 'Kyungsung University', country: 'South Korea', description: 'Dynamic arts and design programs in Busan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80', tags: ['Arts', 'Busan'] },
    { id: 31, degree: 'Modern Economics', university: 'Yeungnam University', country: 'South Korea', description: 'Major private university in Gyeongsan, Gyeongbuk.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80', tags: ['Regional Hub', 'Private'] },
    { id: 32, degree: 'Business Analytics', university: 'Dongguk University', country: 'South Korea', description: 'Located in central Seoul, famous for humanities and business.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80', tags: ['Central Seoul', 'Namsan'] },
    { id: 33, degree: 'Tourism & Leisure', university: 'Silla University', country: 'South Korea', description: 'Located in Busan, focusing on global education.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1512100356956-c1c47f488955?auto=format&fit=crop&q=80', tags: ['Travel', 'Busan'] },
    { id: 34, degree: 'Humanities & Sciences', university: 'Sookmyung Women’s University', country: 'South Korea', description: 'Prestigious women\'s college in Yongsan, Seoul.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80', tags: ['Yongsan', 'Women Only'] },
    { id: 35, degree: 'Engineering & Tech', university: 'Kangwon National University', country: 'South Korea', description: 'State research university in Chuncheon, Gangwon.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80', tags: ['National', 'Gangwon'] },
    { id: 36, degree: 'Global Studies', university: 'Myongji University', country: 'South Korea', description: 'Private university with campuses in Seoul and Yongin.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1454165833767-131ef235c02c?auto=format&fit=crop&q=80', tags: ['Seoul', 'Yongin'] },
    { id: 37, degree: 'Asian Studies', university: 'Dongbang University', country: 'South Korea', description: 'Specialized focus on Asian research and culture.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1493246318656-5bbd4cfb292a?auto=format&fit=crop&q=80', tags: ['Research', 'Culture'] },
    { id: 38, degree: 'Practical Arts', university: 'Howon University', country: 'South Korea', description: 'Located in Gunsan, North Jeolla, focus on applied arts.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1501472312651-726afe119ff1?auto=format&fit=crop&q=80', tags: ['Gunsan', 'Applied Arts'] },
    { id: 39, degree: 'Industrial Design', university: 'Incheon JEI University', country: 'South Korea', description: 'Vocational and technical training in Incheon.', duration: '2-4 Years', image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&q=80', tags: ['Incheon', 'Vocational'] },
    { id: 40, degree: 'International Cooperation', university: 'Keimyung University', country: 'South Korea', description: 'Private university in Daegu with a strong focus on global exchange.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&q=80', tags: ['Daegu', 'Global'] },
    { id: 41, degree: 'Oriental Medicine', university: 'Woosuk University', country: 'South Korea', description: 'Campuses in Wanju and Jincheon, leading in traditional medicine.', duration: '6 Years', image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&q=80', tags: ['Traditional Medicine', 'Wanju'] },
    { id: 42, degree: 'Industrial Engineering', university: 'Sunmoon University', country: 'South Korea', description: 'International-friendly campus in Asan, South Chungcheong.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80', tags: ['International', 'Asan'] },
    { id: 43, degree: 'Ocean Engineering', university: 'University of Ulsan', country: 'South Korea', description: 'Tied closely with Hyundai Heavy Industries, located in Ulsan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1496247749665-49cf5b1022e9?auto=format&fit=crop&q=80', tags: ['Industry Ties', 'Ulsan'] },
    { id: 44, degree: 'National Policy', university: 'Chungnam National University', country: 'South Korea', description: 'Leading national university in Daejeon, the tech hub of Korea.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?auto=format&fit=crop&q=80', tags: ['National', 'Daejeon'] },
    { id: 45, degree: 'Digital Media', university: 'Youngsan University', country: 'South Korea', description: 'Specialized campuses in Busan and Yangsan.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1478720143907-293c660bc4e7?auto=format&fit=crop&q=80', tags: ['Media', 'Busan'] },

    // --- ITALY UNIVERSITIES ---
    {
        id: 301,
        degree: 'Sustainable Fashion Management',
        university: 'Politecnico di Milano',
        country: 'Italy',
        description: 'World-renowned engineering and design university in the fashion capital Milan.',
        duration: '3-4 Years',
        image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?auto=format&fit=crop&q=80',
        tags: ['Global Top 20', 'Design'],
    },
    {
        id: 302,
        degree: 'Global Economics & Finance',
        university: 'Bocconi University',
        country: 'Italy',
        description: 'Premier private university in Milan, a global leader in business education.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80',
        tags: ['Business Leader', 'Milan'],
    },
    {
        id: 303,
        degree: 'Advanced Architecture',
        university: 'University of Bologna',
        country: 'Italy',
        description: 'The oldest university in the Western world, offering historic excellence in Bologna.',
        duration: '3-5 Years',
        image: 'https://images.unsplash.com/photo-1565153229237-db74f76786fb?auto=format&fit=crop&q=80',
        tags: ['Oldest Univ', 'Historic'],
    },
    {
        id: 304,
        degree: 'Data Science & AI',
        university: 'Sapienza University of Rome',
        country: 'Italy',
        description: 'One of the largest and most prestigious universities in Europe, located in Rome.',
        duration: '3-5 Years',
        image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80',
        tags: ['Research Power', 'Rome'],
    },
    {
        id: 305,
        degree: 'Innovation & Entrepreneurship',
        university: 'Politecnico di Torino',
        country: 'Italy',
        description: 'Leading engineering school in Turin with strong industrial ties.',
        duration: '3-5 Years',
        image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80',
        tags: ['Engineering', 'Turin'],
    },
    { id: 306, degree: 'International Law', university: 'University of Milan', country: 'Italy', description: 'Comprehensive research university in Italy\'s economic hub.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80', tags: ['Research', 'Milan'] },
    { id: 307, degree: 'Humanities & Art History', university: 'University of Florence', country: 'Italy', description: 'Study in the cradle of the Renaissance.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?auto=format&fit=crop&q=80', tags: ['Renaissance', 'Arts'] },
    { id: 308, degree: 'Renewable Energy Engineering', university: 'University of Padua', country: 'Italy', description: 'Prestigious university with a legacy spanning 800 years.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1466611653911-954ff21caafc?auto=format&fit=crop&q=80', tags: ['Historic', 'Padua'] },
    { id: 309, degree: 'Digital Media & Communication', university: 'IULM University', country: 'Italy', description: 'Italy\'s premier university for communication and media in Milan.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&q=80', tags: ['Media', 'Communication'] },
    { id: 310, degree: 'Marine Biology', university: 'University of Genoa', country: 'Italy', description: 'Located in the historic port city of Genoa.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1454165833767-131ef235c02c?auto=format&fit=crop&q=80', tags: ['Coastal', 'Genoa'] },
    { id: 311, degree: 'Environmental Sciences', university: 'Ca\' Foscari University of Venice', country: 'Italy', description: 'Study on the historic islands of Venice.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1514890547357-a9ee2887ad8e?auto=format&fit=crop&q=80', tags: ['Venice', 'Sustainability'] },
    { id: 312, degree: 'Business Administration', university: 'LUISS Guido Carli', country: 'Italy', description: 'Top private university in Rome for social sciences.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?auto=format&fit=crop&q=80', tags: ['Business', 'Rome'] },
    { id: 313, degree: 'Cyber Security', university: 'University of Trento', country: 'Italy', description: 'Top-ranked for computer science and engineering in the Alps.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80', tags: ['Mountain View', 'Tech'] },
    { id: 314, degree: 'Agriculture & Food Science', university: 'University of Catania', country: 'Italy', description: 'Located at the foot of Mount Etna in Sicily.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&q=80', tags: ['Sicily', 'Food Science'] },
    { id: 315, degree: 'Gastronomic Sciences', university: 'University of Gastronomic Sciences', country: 'Italy', description: 'The "Slow Food" university in Piedmont.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80', tags: ['Gastronomy', 'Culinary'] },
    { id: 316, degree: 'Fine Arts', university: 'University of Turin', country: 'Italy', description: 'Dynamic study programs in the historic capital of Piedmont.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1501472312651-726afe119ff1?auto=format&fit=crop&q=80', tags: ['Turin', 'Arts'] },
    { id: 317, degree: 'European Studies', university: 'University of Siena', country: 'Italy', description: 'One of Italy\'s most traditional and beautiful university towns.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1534445867742-43195f401b6c?auto=format&fit=crop&q=80', tags: ['Siena', 'Traditional'] },
    { id: 318, degree: 'Mechanical Engineering', university: 'University of Modena', country: 'Italy', description: 'Close ties to the "Motor Valley" (Ferrari, Maserati).', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80', tags: ['Automotive', 'Industry'] },
    { id: 319, degree: 'International Tourism', university: 'University of Palermo', country: 'Italy', description: 'Major research hub in the heart of the Mediterranean.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?auto=format&fit=crop&q=80', tags: ['Palermo', 'Tourism'] },
    { id: 320, degree: 'Applied Genomics', university: 'University of Pavia', country: 'Italy', description: 'Centuries of excellence in medical and biological research.', duration: '2-5 Years', image: 'https://images.unsplash.com/photo-1532187896946-2f5f19086ec4?auto=format&fit=crop&q=80', tags: ['Gene Focus', 'Historic'] },
    { id: 321, degree: 'Civil Engineering', university: 'University of Naples Federico II', country: 'Italy', description: 'One of the world\'s oldest public universities.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?auto=format&fit=crop&q=80', tags: ['Civil', 'Naples'] },
    { id: 322, degree: 'Intercultural Studies', university: 'University for Foreigners of Siena', country: 'Italy', description: 'Specialized in Italian language and culture for global students.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1492538356227-227a7a29555e?auto=format&fit=crop&q=80', tags: ['Language', 'Culture'] },
    { id: 323, degree: 'Global Governance', university: 'University of Pisa', country: 'Italy', description: 'Renowned for research and the elite Scuola Normale Superiore.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80', tags: ['Pisa', 'Governance'] },
    { id: 324, degree: 'Data Driven Economics', university: 'University of Verona', country: 'Italy', description: 'Innovative programs in the city of Romeo and Juliet.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80', tags: ['Verona', 'Economy'] },
    { id: 325, degree: 'Global Business Strategy', university: 'Università Cattolica del Sacro Cuore', country: 'Italy', description: 'Largest private university in Europe, based in Milan.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80', tags: ['Private', 'Milan'] },

    // --- MALTA UNIVERSITIES ---
    {
        id: 401,
        degree: 'Global Maritime Studies',
        university: 'University of Malta',
        country: 'Malta',
        description: 'The premier public university in Malta, offering world-class research in Msida and Valletta.',
        duration: '3-4 Years',
        image: 'https://images.unsplash.com/photo-1590423166649-76137255be1f?auto=format&fit=crop&q=80',
        tags: ['Public Elite', 'Oldest'],
    },
    {
        id: 402,
        degree: 'Applied Applied Sciences & Tech',
        university: 'MCAST',
        country: 'Malta',
        description: 'Malta College of Arts, Science and Technology, leading in vocational and professional training.',
        duration: '2-4 Years',
        image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80',
        tags: ['Technical', 'Career Focus'],
    },
    {
        id: 403,
        degree: 'International Hospitality Management',
        university: 'Institute of Tourism Studies (ITS)',
        country: 'Malta',
        description: 'Dedicated institute for tourism and culinary excellence in the heart of the Mediterranean.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80',
        tags: ['Hospitality', 'Tourism'],
    },
    {
        id: 404,
        degree: 'Digital Business & Innovation',
        university: 'GBSB Global Business School Malta',
        country: 'Malta',
        description: 'International business school in Birkirkara with a focus on digital transformation.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80',
        tags: ['Business', 'Digital'],
    },
    {
        id: 405,
        degree: 'Bachelor of Medicine (MBBS)',
        university: 'Queen Mary University of London – Malta Campus',
        country: 'Malta',
        description: 'Study medicine at a top UK university on the beautiful island of Gozo.',
        duration: '5 Years',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80',
        tags: ['UK Degree', 'Medical'],
    },
    { id: 406, degree: 'International Business', university: 'Global College Malta', country: 'Malta', description: 'Offering modern British education in Żejtun.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1434039345422-4e99e589ed8b?auto=format&fit=crop&q=80', tags: ['British Ed', 'Modern'] },
    { id: 407, degree: 'Accounting & Finance', university: 'London School of Commerce Malta', country: 'Malta', description: 'Global education provider with a focus on business and management in Floriana.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1454165833767-131ef235c02c?auto=format&fit=crop&q=80', tags: ['Global', 'Finance'] },
    { id: 408, degree: 'Industrial Engineering', university: 'American University of Malta', country: 'Malta', description: 'American-style liberal arts education based in Cospicua.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80', tags: ['American Style', 'Cospicua'] },
    { id: 409, degree: 'Strategic Management', university: 'SSBM Malta', country: 'Malta', description: 'Swiss School of Business & Management, providing elite executive education.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80', tags: ['Swiss Degree', 'Executive'] },
    { id: 410, degree: 'Cyber Security & IT', university: 'IDEA Academy Malta', country: 'Malta', description: 'Leading private academy for specialized IT and professional development.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80', tags: ['IT', 'Cyber Sec'] },
    { id: 411, degree: 'Culinary Arts', university: 'Mediterranean Culinary Academy', country: 'Malta', description: 'Master the art of Mediterranean cuisine in Luqa.', duration: '1-3 Years', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80', tags: ['Culinary', 'Specialized'] },
    { id: 412, degree: 'Education Studies', university: 'European Institute of Education', country: 'Malta', description: 'St. Julian\'s hub for academic excellence and pedagogy.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80', tags: ['Education', 'St. Julian\'s'] },
    { id: 413, degree: 'Global Leadership', university: 'European School of Leadership', country: 'Malta', description: 'Developing the next generation of global leaders in Valletta.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80', tags: ['Leadership', 'Valletta'] },
    { id: 414, degree: 'Applied Engineering', university: 'Engineering Institute Malta', country: 'Malta', description: 'Specialized engineering training located in Mosta.', duration: '3-4 Years', image: 'https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80', tags: ['Engineering', 'Mosta'] },
    { id: 415, degree: 'Commercial Pilot Training', university: 'Higher Education Institution Network', country: 'Malta', description: 'Specialized aviation and technical training across multiple cities.', duration: '2-3 Years', image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&q=80', tags: ['Aviation', 'Technical'] },
    { id: 416, degree: 'Health Sciences', university: 'Malta College of Health Sciences', country: 'Malta', description: 'Healthcare training and research in Pembroke.', duration: '3-4 Years', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80', tags: ['Healthcare', 'Research'] },
    { id: 417, degree: 'Digital Innovation', university: 'Malta Digital Innovation Authority', country: 'Malta', description: 'Partnering with global institutes to drive tech excellence in Valletta.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80', tags: ['Tech', 'Innovation'] },
    { id: 418, degree: 'Social Sciences', university: 'St Martin\'s Institute of Higher Education', country: 'Malta', description: 'Long-standing reputation for quality higher education in Hamrun.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1523050853064-8e404bf7622d?auto=format&fit=crop&q=80', tags: ['Quality Ed', 'Hamrun'] },
    { id: 419, degree: 'Supply Chain Management', university: 'Bocconi-Affiliated Network', country: 'Malta', description: 'International business training in Sliema.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80', tags: ['Logistics', 'Sliema'] },
    { id: 420, degree: 'International Finance', university: 'Global Banking School Malta', country: 'Malta', description: 'State-of-the-art finance education in Valletta.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80', tags: ['Banking', 'Valletta'] },

    // --- AUSTRIA UNIVERSITIES ---
    {
        id: 501,
        degree: 'Global Business & Economics',
        university: 'University of Vienna',
        country: 'Austria',
        description: 'Elite research university in the heart of Vienna, over 650 years of academic history.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&q=80',
        tags: ['Academic Excellence', 'Vienna'],
    },
    {
        id: 502,
        degree: 'Advanced Architecture & Design',
        university: 'TU Wien',
        country: 'Austria',
        description: 'Leading technical university in Europe, focusing on innovation and sustainable technology.',
        duration: '3-4 Years',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80',
        tags: ['Technical Leader', 'Vienna'],
    },
    {
        id: 503,
        degree: 'International Management',
        university: 'WU Vienna',
        country: 'Austria',
        description: 'One of the largest and most prestigious business schools in Europe.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1434039345422-4e99e589ed8b?auto=format&fit=crop&q=80',
        tags: ['Business Leader', 'Vienna'],
    },
    {
        id: 504,
        degree: 'Biomedical Innovation',
        university: 'Medical University of Vienna',
        country: 'Austria',
        description: 'One of the oldest and most respected medical schools in the world.',
        duration: '6 Years',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80',
        tags: ['Medical Power', 'Vienna'],
    },
    {
        id: 505,
        degree: 'Applied Data Science',
        university: 'University of Graz',
        country: 'Austria',
        description: 'Traditional research university focusing on sustainable development and digital innovation.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80',
        tags: ['Research Hub', 'Graz'],
    },
    { id: 506, degree: 'Molecular Biology', university: 'University of Innsbruck', country: 'Austria', description: 'Strong focus on life sciences and mountain research.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1532187896946-2f5f19086ec4?auto=format&fit=crop&q=80', tags: ['Innsbruck', 'Science'] },
    { id: 507, degree: 'Sustainable Energy Systems', university: 'TU Graz', country: 'Austria', description: 'Top-tier engineering school in the Styria technology cluster.', duration: '3-5 Years', image: 'https://images.unsplash.com/photo-1466611653911-954ff21caafc?auto=format&fit=crop&q=80', tags: ['Engineering', 'Graz'] },
    { id: 508, degree: 'Global Entrepreneurship', university: 'MCI | The Entrepreneurial School®', country: 'Austria', description: 'International business academy in Innsbruck providing industry-aligned education.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80', tags: ['Business', 'Innsbruck'] },
    { id: 509, degree: 'Natural Resources Management', university: 'BOKU Vienna', country: 'Austria', description: 'Pioneer in sustainability and agricultural sciences.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80', tags: ['Sustainability', 'Vienna'] },
    { id: 510, degree: 'Petroleum Engineering', university: 'University of Leoben', country: 'Austria', description: 'Highly specialized center for mining, metallurgy, and materials.', duration: '4 Years', image: 'https://images.unsplash.com/photo-1481133315263-9585bd3be22f?auto=format&fit=crop&q=80', tags: ['Mining', 'Unique'] },
    { id: 511, degree: 'Software Engineering', university: 'Johannes Kepler University Linz', country: 'Austria', description: 'Innovator in AI and computer science based in Linz.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80', tags: ['AI Focus', 'Linz'] },
    { id: 512, degree: 'International Tourism Management', university: 'Modul University Vienna', country: 'Austria', description: 'Luxury tourism and hospitality education in Vienna.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80', tags: ['Hospitality', 'Private'] },
    { id: 513, degree: 'Digital Media & Design', university: 'Salzburg University of Applied Sciences', country: 'Austria', description: 'Leading applied sciences campus in the cultural hub of Salzburg.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80', tags: ['Salzburg', 'Digital'] },
    { id: 514, degree: 'Health Sciences', university: 'UMIT - Private University', country: 'Austria', description: 'Specialized health informatics and medical technology in Hall in Tirol.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80', tags: ['MedTech', 'Tirol'] },
    { id: 515, degree: 'European Studies', university: 'University of Salzburg', country: 'Austria', description: 'Classical university in the historic UNESCO city of Salzburg.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?auto=format&fit=crop&q=80', tags: ['Classic Ed', 'Salzburg'] },
    { id: 516, degree: 'Renewable Energies', university: 'FH Technikum Wien', country: 'Austria', description: 'Largest university of applied sciences for technical studies in Vienna.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&q=80', tags: ['Technical', 'Tech Hub'] },
    { id: 517, degree: 'Export-Oriented Management', university: 'IMC University of Applied Sciences Krems', country: 'Austria', description: 'International business and health sciences in the scenic Wachau Valley.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1454165833767-131ef235c02c?auto=format&fit=crop&q=80', tags: ['Management', 'Krems'] },
    { id: 518, degree: 'Automotive Engineering', university: 'FH Joanneum', country: 'Austria', description: 'Practical technical education with deep ties to the automotive industry.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80', tags: ['Automotive', 'Industry Ties'] },
    { id: 519, degree: 'Intercultural Psychology', university: 'Sigmund Freud Private University', country: 'Austria', description: 'International psychology hub with a global presence, based in Vienna.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80', tags: ['Psychology', 'Global'] },
    { id: 520, degree: 'Environmental Systems Science', university: 'University of Graz', country: 'Austria', description: 'Highly interdisciplinary research focused on global climate systems.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80', tags: ['Climate', 'Graz'] },

    // --- HUNGARY UNIVERSITIES ---
    {
        id: 601,
        degree: 'Global Business & Economics',
        university: 'Corvinus University of Budapest',
        country: 'Hungary',
        description: 'Elite business and economics education in the heart of Budapest.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80',
        tags: ['Business Leader', 'Budapest'],
    },
    {
        id: 602,
        degree: 'General Medicine (MBBS)',
        university: 'Semmelweis University',
        country: 'Hungary',
        description: 'One of Europe\'s most prestigious medical universities, located in Budapest.',
        duration: '6 Years',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80',
        tags: ['Medical Elite', 'English Taught'],
    },
    {
        id: 603,
        degree: 'Computer Science & AI',
        university: 'Eötvös Loránd University (ELTE)',
        country: 'Hungary',
        description: 'The largest and most prestigious research university in Hungary.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80',
        tags: ['Top Research', 'Budapest'],
    },
    {
        id: 604,
        degree: 'Architecture & Engineering',
        university: 'Budapest University of Technology and Economics (BME)',
        country: 'Hungary',
        description: 'Leading technical university with a legacy of innovation and engineering excellence.',
        duration: '3-4 Years',
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80',
        tags: ['Technical Leader', 'Budapest'],
    },
    {
        id: 605,
        degree: 'International Relations',
        university: 'University of Szeged',
        country: 'Hungary',
        description: 'Consistently ranked among the top universities in Hungary and internationally.',
        duration: '3 Years',
        image: 'https://images.unsplash.com/photo-1434039345422-4e99e589ed8b?auto=format&fit=crop&q=80',
        tags: ['Ranked #1', 'Student City'],
    },
    { id: 606, degree: 'Molecular Biology', university: 'University of Debrecen', country: 'Hungary', description: 'Comprehensive medical and science programs in eastern Hungary.', duration: '3-6 Years', image: 'https://images.unsplash.com/photo-1532187896946-2f5f19086ec4?auto=format&fit=crop&q=80', tags: ['Medical Focus', 'Research'] },
    { id: 607, degree: 'Visual Arts & Design', university: 'Moholy-Nagy University of Art and Design (MOME)', country: 'Hungary', description: 'Premier art and design university with state-of-the-art facilities.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&q=80', tags: ['Art/Design', 'Innovative'] },
    { id: 608, degree: 'Digital Media & Communication', university: 'Budapest Metropolitan University', country: 'Hungary', description: 'Dynamic private university focusing on career-oriented education.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&q=80', tags: ['Career Focused', 'Modern'] },
    { id: 609, degree: 'Psychology', university: 'University of Pécs', country: 'Hungary', description: 'The oldest university in Hungary with a rich clinical history.', duration: '3 Years', image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80', tags: ['Historic', 'Clinical'] },
    { id: 610, degree: 'Mechatronics Engineering', university: 'Óbuda University', country: 'Hungary', description: 'Leading institution for technical and informatics training in Budapest.', duration: '3.5 Years', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80', tags: ['Engineering', 'Budapest'] },
];

